### ISSUE TITLE
invalid image version in example docker-compose

### ISSUE THREAD

**Issue by psimyn** [visiblevc/wordpress-starter#100]
visiblevc/wordpress:0.15.1-php7.1 doesn't seem to exist. I think 'latest-php7.1' are the new tags?

https://github.com/visiblevc/wordpress-starter/blob/master/example/docker-compose.yml#L4

thanks for the repo!

**Comment by karellm** [comment]
@dsifford That's why I don't want us to push to master directly and should always make PRs.

I have [simplified the deploy process](https://github.com/visiblevc/wordpress-starter/wiki/Development), I know it is an extra step from automated builds but can you make sure to deploy to the visiblevc hub repo too when there is a new version?

**Comment by dsifford** [comment]
@karellm The automatic builds work fine actually.

I told you that I was not going to manually update your images here: https://github.com/visiblevc/wordpress-starter/pull/97#issuecomment-303448797

I pushed to master with the patch because you weren't reliably able to respond to PRs in a reasonable window of time and it needed to be fixed.

**Comment by dsifford** [comment]
@psimyn try `dsifford/wordpress:0.15.1-php7.1`

**Comment by karellm** [comment]
@dsifford I don't think it is reasonable to talk about timely fashion when you didn't make a PR or request a review. This is an OS project; I ask you that we don't commit to master directly and make PRs instead. May it be urgent, you can merge it and I will review it later. But there needs to be a track of the changes.

The main issue here though is different. You pushed something to master and as a result there is a mismatch between the docker build and the repo. This is not acceptable since it creates confusion (this issue is the perfect example). When something is merge to master, it *must* be deployed too. I do not wish to be a bottleneck for deploys and would much rather have you manually deploy. May you still not want to manually deploy, I ask you not to push to master or merge PRs. Thanks!

**Comment by karellm** [comment]
@dsifford I will add that I'm not huge on the confusion brought by your fork. I don't mind it, but I don't think it has its place in this repo README or as a recommandation in issues. I know manually deploying is an extra step but it must be done. And if it is done, there is no need for the fork anyway. Thanks!

**Comment by dsifford** [comment]
@karellm Copy, loud and clear. 

@schoenwaldnils Are you still having issues? Have the updated images not been pushed to the visiblevc account?

**Comment by schoenwaldnils** [comment]
@dsifford I cloned the repo, `docker-compose up -d && docker-compose logs -f wordpress` in the example folder and got this:
`ERROR: manifest for visiblevc/wordpress:0.15.1-php7.1 not found`

**Comment by dsifford** [comment]
@schoenwaldnils I just pushed the updated images.

Should be all set to go with `visiblevc/wordpres:0.15.1-php7.1` and the other tags.

**Comment by schoenwaldnils** [comment]
Would be at least nice to wait for an answer before closing this issue.

**Comment by dsifford** [comment]
@schoenwaldnils I don't really appreciate your tone. 

What kind of answer should I be waiting for for this?

The issue was that the tagged images were missing. I resolved that issue.

**Comment by psimyn** [comment]
all is well, working great now. Thanks @dsifford
