### ISSUE TITLE
scripts/install-plugins.sh no output?

### ISSUE THREAD

**Issue by johanbaaij** [visiblevc/wordpress-starter#2]
Me again :). When I run `docker-compose run wordpress /scripts/install-plugins.sh` I get no output in the terminal and no changes on my filesystem. I'm using boot2docker with MyBoot2docker in Windows 10. Any ideas what I could be doing wrong?

**Comment by karellm** [comment]
Can you share the content of your `data/plugins` file?

**Comment by johanbaaij** [comment]
certainly, at first i just had the following;

    advanced-custom-fields

but when I added a line like this;

    advanced-custom-fields
    google-sitemap-generator

I actually got an error

   Install advanced-custom-fields
   curl: (3) Illegal characters found in URL
   .zip.ZIP.or advanced-custom-fieldsed-custom-fields
   rm: cannot remove 'advanced-custom-fields\r.zip': No such file or directory

**Comment by karellm** [comment]
@johanbaaij I'm not using Windows so it will be hard to help you. It looks like your editor uses `\r` rather than `\n` to create a new line. But as you can read here, it won't work on Linux (which is what is running your Wordpress install): http://stackoverflow.com/a/1761086/999540

I highly recommend you configure your editor to use linux-like settings and it should solve your problem.

**Comment by karellm** [comment]
@johanbaaij Any luck with this?

**Comment by johanbaaij** [comment]
@karellm thanks for your reply! i haven't gotten around to trying out your advice yet but you are probably right. will report back once i know more.

**Comment by karellm** [comment]
Closing this for now, feel free to reopen if the bug persists.
