### ISSUE TITLE
Why removing .git, Dockerfile and run.sh?

### ISSUE THREAD

**Issue by joggienl** [visiblevc/wordpress-starter#24]
Thanks for sharing this project! Has some great improvements over "normal" wordpress template development (that's why I would want to use this project)...

I have a question though, the readme file states that you should invoke 'rm -rf .git Dockerfile run.sh' to delete a couple of files. Why is that, it doen't seem necessary?

**Comment by karellm** [comment]
This repository does 2 things:

1. Include the files to create a Docker image
2. Include build tools to develop themes

If you don't plan to build the Docker image yourself, you shouldn't care for 1. We publish the image on Docker Hub and you can grab it directly from there. You basically will never need to build it unless you need to modify it (which you shouldn't need to do 99% of the cases). That's why you can safely remove the `Dockerfile` and `run.sh`. They are already included in the image you get from Docker Hub.

Now why would you want to remote the `.git` folder? Simply because we assume you will start your own repository, named after your project. There is little benefit keeping ties with our git repository, you are better off having your own. We don't have a process to update this starter kit, even running `git pull` from this remote repository could lead to conflicts and problems. It is not ideal but also far from a priority to us at this point.

**Comment by joggienl** [comment]
Thanks for explaining. I think this is valuable information for including in the general documentation (to be able to start using and understanding the project)!

Just a thought of me.. have you ever thought of making a sort of CLI, or something like a yeoman generator for this project? That would ovoid the .git folder "problem". There's indeed no benefit keeping the repository ties. If I would like to change the files from this repo, I would be better of forking it first..

Another benefit could be that it makes it possible to include (or exclude) parts, based on arguments, that don't have my interest.

**Comment by karellm** [comment]
@joggienl I have added a note to the `README`.

As to a CLI, it feels overkill to me. It would obfuscate what's going on and introduce apparent complexity when in reality we just remove files:

- You want your own project? Remove `.git`, `README.md` and `CHANGELOG.md`
- You don't want gulp? Remove `gulpfile.js` and `gulp.json.example`
- You don't want docker? You probably aren't in the right place :smile:

**Comment by joggienl** [comment]
@karellm I saw the update, nice! Thanks.

The .git part actually somehow put me on the wrong track in my mind. Your setup makes the project very flexible indeed. At this point I agree that making it an CLI or generator doesn't add to the projects goal. 

I've thought a little bit more about my previous mention about a CLI or generator. From theme development point of view (or frontend), I do think that having a npm module (or yeoman-generator, or some other scaffolding tool) _using_ this project, would be a huge benefit in kickstarting projects for theme development. Based on some question you could be ready for theme development (and not just ready for setting up for theme development) in seconds. It would make it more repeatable friendly.

Obviously, this would go beyond the fact that this project also allows you to adjust the docker image or the fact that it could be used for plugin development, the deployments, etc, etc.. This other "things" _could_ be hooked from other tools (generators, cli's, what-you-like)...

Sorry for polluting this issue with the generator stuff besides the removal question only. I don't do much with wordpress but I do like using good tools around them. This definitely is one! Thanks for that.

Oh and indeed, if you don't want to use docker chances are rare that you would ever come across this repo anyway :-)

**Comment by karellm** [comment]
@joggienl Arguably we could have 2 repositories, one for the Dockerfile and image generation and one for a generator. If you want to take a stab at a CLI or generator I'm happy to discuss it and assist. Though I can't start that project right now.
