### ISSUE TITLE
Email in local development

### ISSUE THREAD

**Issue by Pushplaybang** [visiblevc/wordpress-starter#48]
Hey there

just using your main docker image, and trying to test email sending but with no joy, any suggestions?

**Comment by dsifford** [comment]
Are you connected to a cloud server or on localhost?

**Comment by dsifford** [comment]
Whoops... I suppose I should have read the title... 

The PHP mailserver doesn't function on localhost. You'll have to send using SMTP. I believe there's a plugin called `wp-mail-smtp` that is pretty popular for doing this.

**Comment by Pushplaybang** [comment]
Hey thanks for the swift response, I've been away from WordPress development for a while, but pretty certain I was able to send mail before.   (as long as I've been doing all sorts of dev, my DevOps experience is pretty light so forgive any ignorance).

I've seen other wp docker stacks that use mail hog to catch local email, which I'd like to do to test transactional email with custom templates etc, but none of them have a great WordPress image  near your configurability etc. I'm pretty certain it was possible to do this with VVV on vagrant.

Are you saying its not possible inside of this setup, or its possible just not setup?

**Comment by dsifford** [comment]
> Are you saying its not possible inside of this setup, or its possible just not setup?

I'm not sure how to set it up. The few times that I've needed to test emails from localhost (even a transactional email service like sendgrid), I've always just used an SMTP plugin like the one I mentioned before.

All that those plugins do is wrap the `wp_mail` function to use SMTP rather than the default mailserver.

That all said, feel free to send in a PR if that doesn't suit your needs and you'd like to set up something like VVV.

**Comment by Pushplaybang** [comment]
@dsifford thanks, yeah im really keen to get this working so will take a crack at it.

**Comment by dsifford** [comment]
Now that I mention that and I start clearing the cobwebs out of my brain this morning, I'm realizing that when I needed to send using sendgrid I _didn't_ have to use a `wp_mail` wrapper plugin because I used their REST api.

I do recall that sendgrid in particular [has their own `wp_mail` wrapper plugin](https://wordpress.org/plugins/sendgrid-email-delivery-simplified/) as well for sites that want to send all email using sendgrid (password resets, welcome emails, etc), rather than additional transactional emails.

Anyway, looking forward to seeing what you can come up with 👍
