### ISSUE TITLE
It should be possible to specify the version of themes and plugins installed from wordpress.org

### ISSUE THREAD

**Issue by louisremi** [visiblevc/wordpress-starter#77]
There's a very good reason why most package managers out there (e.g. NPM, Composer, Docker Hub) make it a good practice of explicitly specifying the version of dependencies: that's because newer versions of dependencies can (and often will) break your project.

wp-cli makes it possible to specify theme and plugin versions. Wordpress starter should not become a dependency manager, but being able to use this feature would be a welcome addition to the tool I believe.

I'm willing to send a PR :-)

**Comment by dsifford** [comment]
In my personal opinion, if you require an older version of some plugin, you should have it downloaded as a local volume. 

Forcing the newest volume on start forces the person to update whatever breaking issue exists with their theme which I think is the right way to go.

I'll let @karellm decide on this. My vote would be no.

**Comment by louisremi** [comment]
I see wordpress-starter as a great way to make developers' life easier. Being forced to fix bugs produced by other people's code isn't the most pleasant chore in my experience. Anyway, this behavior would only be optional and is pretty straightforward to implement (and maintain).

**Comment by dsifford** [comment]
I've run into this scenario more than a few times and it's always been easiest for me to just run `wp plugin install pluginname --version=1.0.0 --activate` to quickly install the plugin at whatever version is causing issues.

I generally don't fix issues as soon as they are reported, but rather wait for 3-5 to build up and tackle all of them at once. So burning the environment and reinstalling everything with some other plugin would be the last thing I'd want to do because of the time it takes.

That said, I'll go along with whatever @karellm decides.

**Comment by dsifford** [comment]
One thing that I would personally recommend is that if you are setting up an environment for the development of a plugin, do not edit your compose file for small issues that arise. The compose file should be everything that you and only you need for your plugin. Use the cli tool to make small tweaks as needed for debugging. Otherwise you'll eventually run into an issue where you forget that you did something to the compose file and waste time debugging something that shouldn't even concern you.

**Comment by louisremi** [comment]
I plan on using wordpress-starter in different scenarios and, you're right, I'll leave my docker-compose.yml mostly untouched when developing plugins :-)

**Comment by karellm** [comment]
First thanks for the interest and contributions. It is very welcome 👍 

I'm a little concerned by the complexity of the project. My tendency would be to follow @dsifford recommandation here. If it is a big hurdle I'm happy to looks at a PR proposal.

**Comment by louisremi** [comment]
It's not a showstopper. Closing for now, but I'll definitely reopen and push again if I ever get bitten by this feature :-)
