### ISSUE TITLE
Trouble with getting the WP_CONTENT_DIR

### ISSUE THREAD

**Issue by musicaljoeker** [visiblevc/wordpress-starter#95]
Hello,

I've been using your WordPress starter kit for a couple months now for dev and it's great, I love it. I'm running into an issue though with the WP_CONTENT_DIR constant in the WordPress codex. Whenever I call this variable, it will return the string `/app/wp-content` which messes with my file system paths when it should be `/wp-content`. What leads me to believe it's an issue with this docker config is that the same code works perfectly without a hitch on a MAMP server. Is there a setting I can throw somewhere to resolve this issue?

Thanks,
Joseph

**Comment by dsifford** [comment]
@musicaljoeker Hi there.

What are you using that for? I believe WordPress recommends using the built-in helper functions rather than [calling the globals directly](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#constants). Have you tried those?

If you're stuck using the globals, you can most likely just define `ABSPATH` in your wp-config.php file to point to `/var/www/html` rather than `/app`, which is [set by WordPress](https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-admin/load-scripts.php#L11). That is likely what's causing your issue. (we symlink that folder to `/app` during the build process).
