### ISSUE TITLE
Add sendmail support to dockerfile

### ISSUE THREAD

**Issue by markv** [visiblevc/wordpress-starter#99]
I'd like to have the ability to specify an smtp server in my docker-compose file so I can use [MailDev](https://hub.docker.com/r/djfarrelly/maildev/) as my development smtp server like this issue: 
https://github.com/djfarrelly/MailDev/issues/115#issuecomment-216831734
 
Can we add sendmail to the dockerfile?

**Comment by dsifford** [comment]
@markv Have you tried one of the various SMTP monkey-patchers that are available as wordpress plugins? (e.g. https://wordpress.org/plugins/wp-mail-smtp/)

Does that not work? You should be able to, at the very least, just create a burner gmail account link up to it via SMTP for testing your emails.

**Comment by markv** [comment]
Yes, I've used that plugin before. I was trying to avoid installing a plugin and keeping the configuration outside of wordpress.

**Comment by dsifford** [comment]
I see.

Unfortunately, since this is a pretty niche need and not really going to be widely needed by a majority of the other users, I'm going to have to recommend just forking this repo and adding in the configuration for yourself. 

We'd really prefer to keep the Dockerfile as slim as we possibly can unless there is a widespread need for  changes to be made.

Thanks for the request nevertheless.
